apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oai-nr-ue.fullname" . }}-uicc
  labels:
    {{- include "oai-nr-ue.labels" . | nindent 4 }}
type: Opaque
stringData:
  nr-ue.yaml: |
    uicc0:
      imsi: {{ .Values.uicc.imsi | quote }}
      key: {{ .Values.uicc.key | quote }}
      opc: {{ .Values.uicc.opc | quote }}
      pdu_sessions:
        - dnn: {{ .Values.uicc.dnn | quote }}
          nssai_sst: {{ .Values.uicc.nssaiSst }}
          nssai_sd: {{ .Values.uicc.nssaiSd }}
    thread-pool: "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"
    rfsimulator:
      - serveraddr: {{ .Values.rfsimulator.serveraddr | quote }}
    {{- if .Values.channelmod.enabled }}
    channelmod:
      max_chan: {{ .Values.channelmod.maxChan }}
      modellist: modellist_rfsimu_1
      modellist_rfsimu_1:
        - model_name: {{ .Values.channelmod.modelNameGnb | quote }}
          type: AWGN
          ploss_dB: {{ .Values.channelmod.pathLossDb }}
          noise_power_dB: {{ .Values.channelmod.noisePowerDb }}
          forgetfact: 0
          offset: 0
          ds_tdl: 0
        - model_name: {{ .Values.channelmod.modelNameUe | quote }}
          type: AWGN
          ploss_dB: {{ .Values.channelmod.pathLossDb }}
          noise_power_dB: {{ .Values.channelmod.noisePowerDb }}
          forgetfact: 0
          offset: 0
          ds_tdl: 0
    {{- end }}
